### ISSUE TITLE
Error when copying card

### ISSUE THREAD

**Issue by robot-from-outer-space** [Arthur-Milchior/anki-copy-note#20] opened 2020-08-29 23:34 UTC
With the newest Anki 2.1.32 I get an error as soon as I try to copy the card with Crtl+C in the browser.

Here is the error report:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.32 (dee7d45d) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-08-30 00:57:00

Caught exception:
Traceback (most recent call last):
  File "C:\Users\p030\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 65, in <lambda>
    a.triggered.connect(lambda: copyNotes(browser.selectedNotes()))
  File "C:\Users\p030\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 52, in copyNotes
    copyNote(nid)
  File "C:\Users\p030\AppData\Roaming\Anki2\addons21\1566928056\copyNote.py", line 83, in copyNote
    note.flush()
  File "anki\notes.py", line 68, in flush
  File "anki\rsbackend_gen.py", line 344, in update_note
  File "anki\rsbackend.py", line 265, in _run_command
anki.rsbackend.NotFoundError

**Comment by Arthur-Milchior** [comment] 2020-08-29 23:57
Probably a duplicate of https://github.com/Arthur-Milchior/anki-copy-note/issues/19

Sorry, I need to find time to deal with this

**Comment by SEE-ICT** [comment] 2020-09-01 16:38
Same problem. Very slightly different traceback. Note the <lambda> at the end of the third line. Dunno if that's helpful, but FWIW:

Caught exception:
Traceback (most recent call last):
  File "D:\Program Data\Anki\addons21\1566928056\copyNote.py", line 65, in <lambda>
    a.triggered.connect(lambda: copyNotes(browser.selectedNotes()))
  File "D:\Program Data\Anki\addons21\1566928056\copyNote.py", line 52, in copyNotes
    copyNote(nid)
  File "D:\Program Data\Anki\addons21\1566928056\copyNote.py", line 83, in copyNote
    note.flush()
  File "anki\notes.py", line 68, in flush
  File "anki\rsbackend_gen.py", line 344, in update_note
  File "anki\rsbackend.py", line 265, in _run_command
anki.rsbackend.NotFoundError

**Comment by Arthur-Milchior** [comment] 2021-02-19 23:54
This should now be corrected. Can you confirm?

**Comment by robot-from-outer-space** [comment] 2021-02-20 00:01
Hi Arthur,
I‘ve checked it with your new version. Now it works like a charm. Thank you
for your time and effort!
Cheers,
Markus

Arthur Milchior <notifications@github.com> schrieb am Sa. 20. Feb. 2021 um
00:55:

**Closed** 2021-02-20 01:49 UTC
